services:
  web:
    # Указываем точное имя образа, который собирает наш CI-пайплайн
    image: skardiz/simple-flask-app:latest
    ports:
      - "8080:5000"
    container_name: my-flask-app-compose
    # Эта политика заставляет Compose всегда проверять,
    # нет ли новой версии образа в Docker Hub
    pull_policy: always
