# Указываем версию синтаксиса. '3.8' - одна из самых распространенных.
version: '3.8'

# 'services' - это главный блок, где мы описываем наши контейнеры.
services:
  # 'web' - это имя нашего сервиса. Мы могли бы назвать его как угодно (app, flask, etc).
  web:
    # 'build: .' говорит Docker Compose, что нужно не скачивать готовый образ,
    # а собрать его из Dockerfile, который лежит в текущей папке ('.').
    build: .
    # 'ports' - это аналог флага -p в команде docker run.
    # Пробрасываем порт 8080 хоста на порт 5000 контейнера.
    ports:
      - "8080:5000"
    # Даем контейнеру статичное имя. Это аналог --name.
    container_name: my-flask-app-compose
