name: CI/CD for Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: skardiz/simple-flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate in Yandex Cloud
        # НОВЫЙ ПРОФЕССИОНАЛЬНЫЙ СПОСОБ:
        # Используем официальный action от Яндекса для аутентификации.
        # Он сам установит и настроит все утилиты.
        uses: yandex-cloud/auth-action@v2
        with:
          # Передаем содержимое key.json напрямую в action
          service_account_key: ${{ secrets.YC_SA_KEY_JSON }}

      - name: Deploy to Kubernetes
        run: |
          # После yandex-cloud/auth-action, утилиты yc и kubectl уже настроены
          yc managed-kubernetes cluster get-credentials my-app-cluster --external
          kubectl apply -f deployment.yaml
