name: CI/CD for Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: skardiz/simple-flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Authenticate in Yandex Cloud
        # Эта команда настраивает yc и kubectl для работы с вашим кластером
        run: |
          # Добавляем наш путь к yc в переменную PATH для текущего шага
          source "/home/runner/yandex-cloud/path.bash.inc"
          
          echo "${{ secrets.YC_SA_KEY_JSON }}" > key.json
          yc config profile create k8s-deployer
          yc config set service-account-key key.json
          # ИСПРАВЛЕНО: Добавляем кавычки вокруг значений
          yc config set cloud-id "${{ secrets.YC_CLOUD_ID }}"
          yc config set folder-id "${{ secrets.YC_FOLDER_ID }}"
          yc managed-kubernetes cluster get-credentials my-app-cluster --external

      - name: Deploy to Kubernetes
        run: |
          # Добавляем наш путь к yc в переменную PATH, чтобы kubectl был доступен
          source "/home/runner/yandex-cloud/path.bash.inc"
          
          kubectl apply -f deployment.yaml
