name: CI/CD for Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: skardiz/simple-flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        run: |
          # Устанавливаем CLI официальным скриптом
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          # ВАЖНО: Добавляем путь к установленному yc в переменную PATH для всех последующих шагов
          echo "/home/runner/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate in Yandex Cloud
        run: |
          # Создаем файл ключа, используя одинарные кавычки для корректной записи
          echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json
          # Настраиваем профиль для аутентификации
          yc config profile create k8s-deployer
          yc config set service-account-key key.json
          
      - name: Deploy to Kubernetes
        run: |
          # Получаем доступ к кластеру. yc и kubectl уже доступны благодаря предыдущим шагам.
          yc managed-kubernetes cluster get-credentials my-app-cluster --external
          # Применяем наш манифест для развертывания приложения
          kubectl apply -f deployment.yaml
