name: CI/CD for Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: skardiz/simple-flask-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # ИСПРАВЛЕНО: Добавляем критически важный шаг скачивания кода
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "/home/runner/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Authenticate in Yandex Cloud
        run: |
          echo '${{ secrets.YC_SA_KEY_JSON }}' > key.json
          yc config profile create k8s-deployer
          yc config set service-account-key key.json
          
      - name: Deploy to Kubernetes
        run: |
          yc managed-kubernetes cluster get-credentials ${{ secrets.K8S_CLUSTER_ID }} --external
          # Теперь эта команда найдет файл, так как он был скачан на шаге Checkout
          kubectl apply -f deployment.yaml
